[package]
name = "dndbot"
version = "0.1.0"
edition = "2021"

[dependencies]
poise = { version = "0.6.1" }
tokio = { version = "1.38.0", features = ["macros", "rt-multi-thread"] }
dotenvy = { version = "0.15.7" }
rand = { version = "0.8.5" }

[profile.release]
strip = "symbols"
lto = "thin"
